name: tr_extension
description: A smart and lightweight string translation through extension.
version: 0.5.1
homepage: https://wwww.branvier.com
repository: https://github.com/arthurbcd/tr_extension.git
topics:
 - smart
 - string
 - extension
 - translation

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1