name: tr_extension
description: A smart and lightweight string translation through extension.
version: 0.1.2
homepage: https://wwww.branvier.com

environment:
  sdk: '>=2.17.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0